[package]
name = "blockforge-rust"
version = "0.1.0"
authors = ["Jakob Gillich <jakob@gillich.me>"]

[dependencies]
url = "1.7.0"
tokio = "0.1.6"
serde = "1.0.64"
serde_json = "1.0.19"
serde_derive = "1.0.64"
mithril = { git = "https://github.com/Ragnaroek/mithril.git", tag = "v0.9.0" }